name: AKS CI
#Install dependencies for the flask python app

on:

  workflow_dispatch:


jobs:
 
  build:
   runs-on: ubuntu-latest
   steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install Dependencies for the app
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
